
# This file will trigger on every push to github,
# it will execute code analysis and unit tests
name: Balance CI

on:
  push:
    branches:
      - master
      - dev/*
      - digit
  pull_request:
    branches:
      - master

jobs:
  test-and-analyze:
    name: Unit Test & Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Install dependencies
        run: flutter pub get

      # Install SQLite libraries for floor tests
      - name: Install SQLite
        run: ./scripts/linux/install_db.sh

      # Generate part files for floor
      - name: Generate part files
        run: ./scripts/linux/build_ci.sh

      # Run Unit Tests
      - name: Unit Test
        run: flutter test

      # Run Code Analysis
      - name: Code Analysis
        run: flutter analyze